version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 004226106633.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-nodejs-app .
      - docker tag my-nodejs-app:latest 004226106633.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 004226106633.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest
      # ПЕРЕНОСИМ ФАЙЛ В КОРЕНЬ И ЧИСТИМ ЕГО
      - cp scripts/after_install.sh ./deploy_script.sh
      - sed -i 's/\r$//' deploy_script.sh
      - chmod +x deploy_script.sh

artifacts:
  files:
    - appspec.yml
    - deploy_script.sh
  discard-paths: yes
